export const LOGIN_REQUEST ="LOGIN_REQUEST"
export const LOGIN_FAILURE ="LOGIN_FAILURE"
export const LOGIN_REQUEST_SAGA ="LOGIN_REQUEST_SAGA"
export const LOGIN_FAILURE_SAGA ="LOGIN_FAILURE_SAGA"
export const LOGIN_SUCCESS_SAGA ="LOGIN_SUCCESS_SAGA"




